server:
  port: 80

spring:
  application:
    name: cloud-order-service
  cloud:
    consul:
      host: 39.97.188.145
      port: 8500
      discovery:
        service-name: ${spring.application.name}
