server:
  port: 9002
spring:
  application:
    name: cloudalibaba-provider-payment-service
  cloud:
    nacos:
      discovery:
        server-addr: 39.97.188.145:8888
      #server-addr: 39.97.188.145:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"
