server:
  port: 9003

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 39.97.188.145:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"
