server:
  port: 8001


spring:
  application:
    name: cloud-payment-service
  spring:
    zikpin:
      base-url: http://xxx.xxx.xxx.xxx:9411
  sleuth:
    sampler:
      probability: 1
  datasource:
    url: jdbc:mysql://localhost:3306/cloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 199916aa
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.cloneman.springcloud.dao:
      debug

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: payment8001
    prefer-ip-address: true  #展示id信息
    